require('general')
require('plugins')
require('theme')
require('keymap')

require('configs.treesitter')
require('configs.lualine')
require('configs.bufferline')
require('configs.nvimtree')
require('configs.telescope')
require('configs.whichkey')
require('configs.autopairs')
