require('general')
require('plugins')
require('theme')
require('keymap')
require('autorun')

require('configs.treesitter')
require('configs.lualine')
require('configs.bufferline')
require('configs.nvimtree')
require('configs.telescope')
require('configs.whichkey')
require('configs.autopairs')
require('configs.lsp.cmp')
require('configs.lsp.diagnostics')
require('configs.lsp.servers')

